- name: Create folders
  ansible.builtin.include_tasks: folder.yml

  loops:
    - CIPipelines
  vars:
    TEMPLATE: folder.xml

- name: Include Pipeline Jobs File
  ansible.builtin.include_tasks: pipeline.yml
  loops:
    - {name: "frontend", dir: "CIPiplines"}
    - {name: "cart", dir: "CIPiplines"}
  vars:
    TEMPLATE: pipeline.xml