- name: create config file
  ansible.builtin.template:
    src: job.xml
    dest: /temp/job.xml


- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/temp/job.xml') }}"
    name: test
    url: 172.31.20.105:8080
    user: admin
    password: "{{jenkins_password}}"
  loops:
    - frontend
    - cart
