- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item}}"
    url: 172.31.20.105:80:8080
    user: admin
    password: "{{jenkins_password}}"
  loops:
    - CIPlines

- name: Include Pipeline Jobs File
  ansible.builtin.include_tasks: pipeline.yml
  loops:
    - {name: "frontend", dir: "CIPlines"}
    - {name: "cart", dir: "CIPlines"}