- name: create  Pipeline Jobs File
  ansible.builtin.include_tasks: pipeline.yml
  loops:
    - {name: "frontend", dir: "CIPiplines"}
    - {name: "cart", dir: "CIPiplines"}
  vars:
    TEMPLATE: pipeline.xml