- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: ""{{item}}"
    url: http://172.31.3.12:8080
    user: admin
    password: "{{jenkins_password}}"
  loops: "{{ folders }}"

- name: create  Pipeline Jobs File
  ansible.builtin.include_tasks:
    file: pipeline.yml
  loops: "{{ pipeline_jobs }}"



