#- name: create config file
#  ansible.builtin.templates:
#    src: folder.xml
#    dest: /tmp/job.xml
#
#
#- name: Create a jenkins job
#  community.general.jenkins_job:
#    config: "{{ lookup('file', '/tmp/folder.xml') }}"
#    name: ""{{item.dir}}"
#    url: 3.237.80.60:8080
#    user: admin
#    password: "{{jenkins_password}}"
#
#- name: create config file
#  ansible.builtin.templates:
#    src: job.xml
#    dest: /tmp/job.xml
#
#
#- name: Create a jenkins job
#  community.general.jenkins_job:
#    config: "{{ lookup('file', '/tmp/job.xml') }}"
#    name: ""{{item.dir}/{item.name}"
#    url: 3.237.80.60:8080
#    user: admin
#    password: "{{jenkins_password}}"